# Generated by Django 2.0.6 on 2018-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
